---
galaxy_info:
  author: Sensor Factory
  description: Install, configure and validate the SenHub Agent.
  company: Sensor Factory
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bullseye, bookworm]
    - name: Ubuntu
      versions: [jammy, noble]
    - name: EL
      versions: ["8", "9"]
    - name: opensuse
      versions: ["15"]
    - name: Windows
      versions: [all]
  galaxy_tags: [monitoring, observability, opentelemetry, senhub]
dependencies: []
