project_name: senhub-agent

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/agent/main.go
    binary: senhub-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
    ldflags:
      - -s -w
      - -X senhub-agent.go/internal/agent/cliArgs.Version={{.Version}}
      - -X senhub-agent.go/internal/agent/cliArgs.CommitHash={{.Commit}}
      - -X senhub-agent.go/internal/agent/cliArgs.BuildTime={{.Date}}
      - -X senhub-agent.go/internal/agent/cliArgs.GoVersion={{.Env.GOVERSION}}
      - -X senhub-agent.go/internal/agent/cliArgs.Env=production
      - -X senhub-agent.go/internal/agent/cliArgs.ProductionURL=https://eu-west-1.intake.senhub.io
      - -X senhub-agent.go/internal/agent/cliArgs.DevelopmentURL=https://eu-west-1.intake-dev.senhub.io

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*  # This ensures only binaries are included, no source files

source:
  enabled: false  # This disables source code in releases

changelog:
  skip: true  # This disables changelog generation

checksum:
  name_template: 'checksums.txt'
