before:
  hooks:
    - go mod tidy

builds:
  - id: "senhub-agent"
    main: ./cmd/agent/main.go
    binary: "senhub-agent"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X senhub-agent.go/internal/agent/cliArgs.Version={{.Version}}
      - -X senhub-agent.go/internal/agent/cliArgs.CommitHash={{.Commit}}
      - -X senhub-agent.go/internal/agent/cliArgs.BuildTime={{.Date}}
      - -X senhub-agent.go/internal/agent/cliArgs.GoVersion={{.Env.GOVERSION}}
      - -X senhub-agent.go/internal/agent/cliArgs.Env=production
      - -X senhub-agent.go/internal/agent/cliArgs.ProductionURL=https://eu-west-1.intake.senhub.io
      - -X senhub-agent.go/internal/agent/cliArgs.DevelopmentURL=https://eu-west-1.intake-dev.senhub.io

archives:
  - id: binary-archives
    format: binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    allow_different_binary_count: true

release:
  draft: false
  prerelease: auto
  mode: replace

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

source:
  enabled: false

changelog:
  skip: true
