#!/bin/zsh

# Définition de la clé d'authentification et de l'URL du serveur
#AUTH_KEY="2a197eb3-4225-4e7b-8ed1-fdec21a2a839"
#SERVER_URL="http://127.0.0.1:8080"

AUTH_KEY="23b21493-990c-42dd-993c-1e99ab61b9d2"
SERVER_URL="https://eu-west-1.intake.senhub.io"

# Exécution de la commande avec les arguments
./senhub-agent_darwin_amd64 --authentication-key "$AUTH_KEY" --server-url "$SERVER_URL"
