agent:
  key: "test-metrics-audit"
  mode: offline

storage:
  - name: http
    params:
      port: 8080
      bind_address: "127.0.0.1"
      endpoints: ["prtg", "senhub", "nagios"]

probes:
  - name: cpu
    params:
      interval: 30

  - name: memory
    params:
      interval: 30

  - name: network
    params:
      interval: 30

  - name: logicaldisk
    params:
      interval: 30

  - name: ping_gateway
    params:
      interval: 60