package main

import (
	"fmt"
	"os"
	"strings"
)

// handleDbMonitoringCommand dispatches the `senhub-agent
// db-monitoring …` subcommands. v1 ships a single subcommand:
// `init` — prints the SQL GRANT block for the requested engine.
//
// This is the operator-friendly helper from DESIGN §5.8. The
// command does NOT connect to a database — DBAs paste, audit, run.
// Available to all users regardless of license tier (a marketing
// hook for the database probes).
func handleDbMonitoringCommand() {
	// db-monitoring init …
	if len(os.Args) < 3 {
		printDbMonitoringHelp()
		os.Exit(2)
	}
	sub := os.Args[2]
	switch sub {
	case "init":
		handleDbMonitoringInit(os.Args[3:])
	case "--help", "-h", "help":
		printDbMonitoringHelp()
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand: db-monitoring %s\n\n", sub)
		printDbMonitoringHelp()
		os.Exit(2)
	}
}

func printDbMonitoringHelp() {
	fmt.Println(`senhub-agent db-monitoring — helpers for the database probes

USAGE
  senhub-agent db-monitoring init --engine <mysql|postgresql> --user <name>

  Prints the SQL GRANT block needed by the senhub-agent monitoring
  user. The command does NOT connect to the database; copy the
  output, paste it into your DBA shell, audit it, and run it.

FLAGS
  --engine NAME    mysql, mariadb, or postgresql
  --user NAME      Monitoring user to create (default: senhub_monitor)
  --host HOST      Source host for the MySQL grant (default: %, all hosts)
  --version N      Major engine version, used to gate version-specific
                   grants. Optional — defaults pick the safest superset.

EXAMPLES
  senhub-agent db-monitoring init --engine postgresql
  senhub-agent db-monitoring init --engine mysql --user mon_user --host 10.0.0.5
`)
}

func handleDbMonitoringInit(args []string) {
	engine := ""
	user := "senhub_monitor"
	host := "%"
	version := 0

	// Tiny hand-rolled flag parser — go-arg would do but adding a
	// new arg struct in cliArgs/ for a one-off command would be
	// noise. The flag set is small enough that the loop below is
	// auditable at a glance.
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--engine" && i+1 < len(args):
			engine = strings.ToLower(args[i+1])
			i++
		case a == "--user" && i+1 < len(args):
			user = args[i+1]
			i++
		case a == "--host" && i+1 < len(args):
			host = args[i+1]
			i++
		case a == "--version" && i+1 < len(args):
			// Parse but tolerate garbage — version is optional
			// and the safe default applies if we can't read it.
			_, _ = fmt.Sscanf(args[i+1], "%d", &version)
			i++
		case a == "--help", a == "-h":
			printDbMonitoringHelp()
			return
		default:
			fmt.Fprintf(os.Stderr, "unknown flag: %s\n\n", a)
			printDbMonitoringHelp()
			os.Exit(2)
		}
	}

	if engine == "" {
		fmt.Fprintln(os.Stderr, "error: --engine is required\n")
		printDbMonitoringHelp()
		os.Exit(2)
	}

	switch engine {
	case "mysql", "mariadb":
		printMySQLGrant(user, host)
	case "postgresql", "postgres", "pg":
		printPostgreSQLGrant(user)
	default:
		fmt.Fprintf(os.Stderr, "unsupported engine: %q (want mysql|mariadb|postgresql)\n", engine)
		os.Exit(2)
	}
}

func printMySQLGrant(user, host string) {
	fmt.Printf(`-- SenHub Agent — MySQL / MariaDB monitoring user
-- Generated by: senhub-agent db-monitoring init --engine mysql
--
-- Review before running. Replace 'STRONG-PASSWORD-HERE' with a
-- generated secret and store the password in the senhub-agent
-- YAML (or via the env-var ${env:MYSQL_MONITOR_PASSWORD}).
--
-- Grants explained:
--   PROCESS              — SHOW PROCESSLIST, threads_running
--   REPLICATION CLIENT   — SHOW SLAVE / REPLICA STATUS
--   SELECT ON *.*        — read information_schema and
--                          performance_schema views
--   SLAVE MONITOR        — MariaDB 10.5.8+ only (drop the line
--                          on older MariaDB and any MySQL)

CREATE USER '%s'@'%s' IDENTIFIED BY 'STRONG-PASSWORD-HERE';
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '%s'@'%s';

-- For MariaDB 10.5.8+ only:
-- GRANT SLAVE MONITOR ON *.* TO '%s'@'%s';

FLUSH PRIVILEGES;
`, user, host, user, host, user, host)
}

func printPostgreSQLGrant(user string) {
	fmt.Printf(`-- SenHub Agent — PostgreSQL monitoring user
-- Generated by: senhub-agent db-monitoring init --engine postgresql
--
-- Review before running. Replace 'STRONG-PASSWORD-HERE' with a
-- generated secret and store the password in the senhub-agent
-- YAML (or via env-var ${env:PG_MONITOR_PASSWORD}).
--
-- The pg_monitor role bundles read access to pg_stat_*,
-- pg_stat_activity (full visibility), pg_stat_replication and
-- pg_stat_archiver. Available since PG 10. For PG 9.x you need
-- per-view GRANTs — out of scope for v1.

CREATE ROLE %s LOGIN PASSWORD 'STRONG-PASSWORD-HERE';
GRANT pg_monitor TO %s;

-- Optional: enable pg_stat_statements for query-level metrics
-- (DESIGN §5.4). Needs a superuser + shared_preload_libraries
-- restart.
--
-- ALTER SYSTEM SET shared_preload_libraries = 'pg_stat_statements';
-- -- restart the server, then:
-- CREATE EXTENSION pg_stat_statements;
`, user, user)
}
