baseURL = "https://docs.senhub.io/"
title = "SenHub Agent Documentation"
theme = "hugo-book"

defaultContentLanguage = "en"
enableGitInfo = true

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"
  BookLogo = "logo.png"
  BookRepo = "https://github.com/senhub-io/senhub-agent"
  BookSearch = true
  BookDateFormat = "January 2, 2006"
  BookMenuBundle = "/menu"
  BookComments = false
  AgentVersion = "0.1.80-beta"

[markup]
  [markup.highlight]
    style = "github"
    lineNos = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
