name: Dev Tag Release
on:
  push:
    branches: [ dev ]
    tags:
      - '*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'
      - name: Get Go Version
        id: go_version
        run: |
          GO_VERSION=$(go version | cut -d' ' -f3)
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV
      - name: Get Tag Version and Create Beta Tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          BETA_TAG="${TAG}-beta"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "BETA_TAG=$BETA_TAG" >> $GITHUB_ENV
      - name: Create Beta Tag
        run: |
          git tag ${{ env.BETA_TAG }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GOVERSION: ${{ env.GO_VERSION }}
      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BETA_TAG }}
          name: Beta Release ${{ env.BETA_TAG }}
          files: |
            dist/senhub-agent_linux_*
            dist/senhub-agent_windows_*
            dist/senhub-agent_darwin_*
            dist/metadata.json
          generate_release_notes: false
          prerelease: true