name: Go-test-windows
on:
  push:
    branches: [dev, master]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.keys/**'
  pull_request:
    branches: [dev, master]
    paths-ignore:
      - 'docs/**'
      - '*.md'
env:
  SENHUB_KEY: "test-key"

jobs:
  test-and-build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Test with the Go CLI
        run: make test

      - name: Build
        env:
          GOOS: windows
          GOARCH: amd64
          ENV: production
        run: make build

      - name: Test Windows Service
        shell: powershell
        run: |
          if (Test-Path -Path ".\scripts\test_windows_service.ps1") {
            .\scripts\test_windows_service.ps1
          } else {
            Write-Host "Service test script not found, skipping"
          }
