before:
  hooks:
    - go mod tidy
builds:
  - id: "senhub-agent"
    main: ./cmd/agent/main.go
    binary: "senhub-agent"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X senhub-agent.go/internal/agent/cliArgs.Version={{.Version}}
      - -X senhub-agent.go/internal/agent/cliArgs.CommitHash={{.Commit}}
      - -X senhub-agent.go/internal/agent/cliArgs.BuildTime={{.Date}}
      - -X senhub-agent.go/internal/agent/cliArgs.GoVersion={{.Env.GOVERSION}}
      - -X senhub-agent.go/internal/agent/cliArgs.Env=production
      - -X senhub-agent.go/internal/agent/cliArgs.ProductionURL=https://eu-west-1.intake.senhub.io
      - -X senhub-agent.go/internal/agent/cliArgs.DevelopmentURL=https://eu-west-1.intake-dev.senhub.io
    dir: .
archives:
  - id: binaries
    format: binary
    name_template: "{{ .Binary }}"
    wrap_in_directory: false
    files:
      - none*
    allow_different_binary_count: true
    builds:
      - senhub-agent
    strip_parent_binary_name: true
release:
  draft: false
  mode: replace
  make_latest: true
signs:
  - artifacts: none
source:
  enabled: false
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
